version: '3'

services:

  app:
    container_name: nginx-node-mongo
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    links:
      - webserver
      - mongo

  webserver:
    image: "registry.mygit.th-deg.de/ka21180/clustering-mit-docker:rnginx"
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"

  mongo:
    container_name: mongo
    image: "registry.mygit.th-deg.de/ka21180/clustering-mit-docker:rmongodb"
    restart: unless-stopped
    ports:
      - '27017:27017'
