version: '3.7'

services:

  nodejs:
    image: "registry.mygit.th-deg.de/ka21180/clustering-mit-docker:nodejs"
    ports:
      - "3000:3000"
    deploy:
      replicas: 3

  nginx:
    image: "registry.mygit.th-deg.de/ka21180/clustering-mit-docker:nginx"
    ports:
      - "80:80"
    deploy:
      replicas: 3

  mongo:
    image: "registry.mygit.th-deg.de/ka21180/clustering-mit-docker:mongo"
    ports:
      - '27017:27017'
    deploy:
      replicas: 3

